global_frame: map
rolling_window: false
track_unknown_space: false
width: 10.0
height: 10.0
origin_x: -5.0
origin_y: -5.0
resolution: 0.05
static_map: true

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,               type: "costmap_2d::InflationLayer"}
