controller_frequency: 5.0
recovery_behaviour_enabled: true

TrajectoryPlannerROS:

  # Robot Configuration Parameters
  acc_lim_x: 10.0
  acc_lim_y: 10.0
  acc_lim_theta:  20.0

  max_vel_x: 0.5
  min_vel_x: 0.1

  max_vel_y: 0.5
  min_vel_y: 0.1

  max_vel_theta: 1.57
  min_vel_theta: -1.57
  min_in_place_vel_theta: 0.314

  holonomic_robot: true
  escape_vel: -0.5

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.157
  xy_goal_tolerance: 0.25
  latch_xy_goal_tolerance: false

  # Forward Simulation Parameters
  sim_time: 2.0
  sim_granularity: 0.02
  angular_sim_granularity: 0.02
  vx_samples: 6
  vtheta_samples: 20
  controller_frequency: 20.0

  # Trajectory scoring parameters
  meter_scoring: true # Whether the gdist_scale and pdist_scale parameters should assume that goal_distance and path_distance are expressed in units of meters or cells. Cells are assumed by default (false).
  occdist_scale:  0.1 #The weighting for how much the controller should attempt to avoid obstacles. default 0.01
  pdist_scale: 0.75  #     The weighting for how much the controller should stay close to the path it was given . default 0.6
  gdist_scale: 1.0 #     The weighting for how much the controller should attempt to reach its local goal, also controls speed  default 0.8

  heading_lookahead: 0.325  #How far to look ahead in meters when scoring different in-place-rotation trajectories
  heading_scoring: true  #Whether to score based on the robot's heading to the path or its distance from the path. default false
  heading_scoring_timestep: 0.8   #How far to look ahead in time in seconds along the simulated trajectory when using heading scoring (double, default: 0.8)
  dwa: true #Whether to use the Dynamic Window Approach (DWA)_ or whether to use Trajectory Rollout
  simple_attractor: false
  publish_cost_grid_pc: true

  #Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05 #How far the robot must travel in meters before oscillation flags are reset (double, default: 0.05)
  escape_reset_dist: 0.1
  escape_reset_theta: 0.1

DWAPlannerROS:
  holonomic_robot: true

  # Tolerances                  Defaults
  yaw_goal_tolerance: 0.05      # 0.05
  xy_goal_tolerance:  0.05      # 0.10
  latch_xy_goal_tolerance: true # false

  # Forward simulation          Defaults
  use_dwa: true                 # true
  sim_time: 1.7                 # 1.7
  sim_granularity: 0.025        # 0.025
  angular_sim_granularity: 0.017 # 0.10 (1 degree = 0.017 rad)
  vx_samples: 20                 # 10
  vy_samples: 20                # 10
  vth_samples: 20               # 20

  # Scoring                     Defaults
  meter_scoring: false          # Is this even taken into account?
  path_distance_bias: 32.00      # 32.0
  goal_distance_bias: 24.0      # 24.0
  occdist_scale: 0.01           # 0.01
  forward_point_distance: 0.325 # 0.325
  stop_time_buffer: 0.20        # 0.20
  scaling_speed: 0.25           # 0.25
  max_scaling_factor: 0.20      # 0.20
  heading_lookahead: 0.325
  heading_scoring_timestep: 0.8
  heading_scoring: false         # Is this even taken into account?
  penalize_negative_x: false    # Is this even taken into account?

  # Acceleration and velocity limits

  # acc_limit_trans: 1.0
  acc_lim_x: 1.0                # 2.5
  acc_lim_y: 1.0                # 2.5
  acc_lim_theta: 1.0            # 3.2

  # max_trans_vel: 0.5
  # min_trans_vel: 0.1
  max_vel_x: +0.3
  min_vel_x: -0.3
  max_vel_y: +0.5
  min_vel_y: -0.5

  max_rot_vel: 1.0
  min_rot_vel: 0.4

  # Other                       Defaults
  oscillation_reset_dist: 0.05  # 0.05
  oscillation_reset_angle: 0.20 # 0.20
  prune_plan: false             # true
  trans_stopped_vel: 0.1        # 0.1
  rot_stopped_vel: 0.1          # 0.1
  publish_cost_grid_pc: true    # false

TebLocalPlannerROS:
 # Trajectory
 teb_autosize: True
 dt_ref: 0.3
 dt_hysteresis: 0.1
 max_samples: 500
 global_plan_overwrite_orientation: True
 allow_init_with_backwards_motion: False
 max_global_plan_lookahead_dist: 3.0
 global_plan_viapoint_sep: -1
 global_plan_prune_distance: 1
 exact_arc_length: False
 feasibility_check_no_poses: 5
 publish_feedback: False
    
 # Robot      
 max_vel_x: 0.5
 max_vel_x_backwards: 0.5
 max_vel_y: 0.5
 max_vel_theta: 2
 acc_lim_x: 0.5
 acc_lim_y: 0.5
 acc_lim_theta: 2
 min_turning_radius: 0.0 # omni-drive robot (can turn on place!)

 footprint_model:
   type: "point"

 # GoalTolerance
 xy_goal_tolerance: 0.2
 yaw_goal_tolerance: 0.1
 free_goal_vel: False
 complete_global_plan: True
    
 # Obstacles 
 min_obstacle_dist: 0.25 # This value must also include our robot radius, since footprint_model is set to "point".
 inflation_dist: 0.6
 include_costmap_obstacles: True
 costmap_obstacles_behind_robot_dist: 1.0
 obstacle_poses_affected: 15
 costmap_converter_plugin: ""
 costmap_converter_spin_thread: True
 costmap_converter_rate: 5

 # Optimization
 no_inner_iterations: 5
 no_outer_iterations: 4
 optimization_activate: True
 optimization_verbose: False
 penalty_epsilon: 0.1
 obstacle_cost_exponent: 4
 weight_max_vel_x: 2
 weight_max_vel_y: 2
 weight_max_vel_theta: 1
 weight_acc_lim_x: 1
 weight_acc_lim_y: 1
 weight_acc_lim_theta: 1
 weight_kinematics_nh: 0 # WE HAVE A HOLONOMIC ROBOT, JUST ADD A SMALL PENALTY
 weight_kinematics_forward_drive: 0
 weight_kinematics_turning_radius: 0
 weight_optimaltime: 1 # must be > 0
 weight_shortest_path: 0
 weight_obstacle: 100
 weight_inflation: 0.2
 weight_dynamic_obstacle: 10
 weight_dynamic_obstacle_inflation: 0.2
 weight_viapoint: 1
 weight_adapt_factor: 2

 # Homotopy Class Planner
 enable_homotopy_class_planning: True
 enable_multithreading: True
 max_number_classes: 4
 selection_cost_hysteresis: 1.0
 selection_prefer_initial_plan: 0.9
 selection_obst_cost_scale: 1.0
 selection_alternative_time_cost: False
 
 roadmap_graph_no_samples: 15
 roadmap_graph_area_width: 5
 roadmap_graph_area_length_scale: 1.0
 h_signature_prescaler: 0.5
 h_signature_threshold: 0.1
 obstacle_heading_threshold: 0.45
 switching_blocking_period: 0.0
 viapoints_all_candidates: True
 delete_detours_backwards: True
 max_ratio_detours_duration_best_duration: 3.0
 visualize_hc_graph: False
 visualize_with_time_as_z_axis_scale: False

# Recovery
 shrink_horizon_backup: True
 shrink_horizon_min_duration: 10
 oscillation_recovery: True
 oscillation_v_eps: 0.1
 oscillation_omega_eps: 0.1
 oscillation_recovery_min_duration: 10
 oscillation_filter_duration: 10

EBandPlannerROS:
  # common parameters
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.05
  rot_stopped_vel: 0.01
  trans_stopped_vel: 0.01

  # visualization parameters
  marker_lifetime: 0.5

  # eband local planner parameters
  eband_min_relative_overlap: 1.4
  eband_tiny_bubble_distance: 0.01  
  eband_tiny_bubble_expansion: 0.01  
  eband_internal_force_gain: 1.0  
  eband_external_force_gain: 2.0  
  num_iterations_eband_optimization: 3
  eband_equilibrium_approx_max_recursion_depth: 4
  eband_equilibrium_relative_overshoot: 0.75  
  eband_significant_force_lower_bound: 0.15  
  costmap_weight: 10.0  

# trajectory controller parameters
  max_vel_lin: 0.5 
  max_vel_th: 1.5  
  min_vel_lin: 0.01  
  min_vel_th: 0.0  
  min_in_place_vel_th: 0.0  
  in_place_trans_vel: 0.0  
  k_prop: 4.0  
  k_damp: 3.5  
  Ctrl_Rate: 10.0  
  max_acceleration: 0.8  
  virtual_mass: 0.75
  max_translational_acceleration: 0.8  
  max_rotational_acceleration: 1.5  
  rotation_correction_threshold: 0.5  
  differential_drive: False
  bubble_velocity_multiplier: 2.0  
  rotation_threshold_multiplier: 1.0  
  disallow_hysteresis: False
